### ISSUE TITLE
Wyłączanie się programu

### ISSUE THREAD

**Issue by Vaciak98** [AbdShullah/ShindenToAnilist#1]
Jest szansa na aktualizację? Program po wpisaniu nicku wyłącza się, nie ze wszystkimi, ale z moim tak.

**Comment by Kacper-Kondracki** [comment]
Dzieje się tak, ponieważ program polega na przetwarzaniu kodu HTML twojej listy anime. Przystosowałem to do domyślnych ustawień więc by zadziałało musisz zresetować ustawienia i wygląd swojej listy. 
Warto też samemu zaktualizować bazę danych anime.

**Comment by Vaciak98** [comment]
Ok już wiem gdzie leżał problem. Program używa starej listy shindena https://shinden.pl/animelist/  a teraz jest nowa pod adresem https://lista.shinden.pl

**Comment by rurzowiutki** [comment]
> Ok już wiem gdzie leżał problem. Program używa starej listy shindena https://shinden.pl/animelist/ a teraz jest nowa pod adresem https://lista.shinden.pl

### **Powiesz proszę jak dokładnie to zrobiłeś?** 

Wiem jak uruchomić starą listę na Shinden, mam domyślne ustawienia, wrzuciłem default css, więc wszystko jest jak fabryka dała, porównywałem sobie nawet z innymi użytkownikami. W ustawieniach również uruchamiałem tryb zgodności z myanimelist i go wyłączałem - to niczego nie zmieniało.
Jednak nie wiem co zmienia Twój komentarz. Skoro program prosi o **podanie nazwy użytkownika - jest ona taka sama jak w przypadku starej listy**, także trochę nie rozumiem Twojej wskazówki. Brzmi to zupełnie tak, **jakbyś wprowadzał adres** do swojej listy. Czy to tak należy postąpić?

Uzupełniam nazwę użytkownika o ostatnią część adresu www, czyli **ID-nazwauzytkownika**, np. 3422534-trelemorele i program się zamyka. Gdy wprowadzę samo ID, czyli 3422534 albo samą nazwę użytkownika - również się zamyka. Uzupełniam adresem do pełnej listy, uzupełniam w formie ID-nazwauzytkownika/all - też się zamyka.

Udało mi się uchwycić listę zdarzeń, które się na sekundę pojawiają przed zamknięciem programu, może to w czymś pomoże:

![shindentomal](https://github.com/Kacper-Kondracki/ShindenToAnilist/assets/96441372/4d0b2f4c-3afa-49a8-9acf-7fa69fb7d483)


Testowane na Win10Home64bit z prawami Administratora i bez. Zapora wyłączona, brak antywirusa.

// Przenoszenie **blisko 400 tytułów** to będzie jakaś masakra, więc gdyby chociaż połowę przeniosło, byłbym niebywale uradowany, szczególnie z racji, że korzystam już prawie tylko z anglojęzycznych stron WWW. 

### **Proszę o pomoc i z góry dziękuję za potencjalne zaangażowanie.**

**Comment by Vaciak98** [comment]
Musisz starą listę z https://shinden.pl/animelist w ustawieniach przywrócić
do ustawień fabrycznych. Usuń style css i tak dalej.

czw., 19 paź 2023 o 05:29 rurzowiutki ***@***.***> napisał(a):

**Comment by Kacper-Kondracki** [comment]
Przywróć starą listę do domyślnych ustawień, ważne, by odpowiednie kolumny były zaznaczone

[image.png]

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by Kacper-Kondracki** [comment]
@Vaciak98 
Zajmę się przepisaniem tego programu do Rusta. Nowa lista anime korzysta z API, które wypluwa rekordy w jsonie, więc ułatwili mi zadanie.

**Comment by rurzowiutki** [comment]
Nie wiem gdzie tam jest w ogóle opcja przywracania ustawień domyślnych tego CSS, więc albo jej nie ma albo jestem ślepy.

_(Nawet teraz szukam i nie widzę. W ogólnych są kolumny, dźwięki i inne, w "Prostym generatorze wyglądu" są zakładki: Nagłówek, Tabela, Obramowanie, Tła i sekcje, Belka statusów, Rozmieszczenie, Generuj kod, Załaduj Zewnętrzne i Zewnętrzny CSS i w żadnym z nich nie ma słowa o domyślnych ustawieniach, taką opcję znalazłem tylko w tej nowej liście w zakładce Generator wyglądu - ogólne. No, ale on chyba nie sprawi, że stara lista też się zresetuje, prawda? Sprawdziłem aż na innej przeglądarce, pokasowałem cookies i cache - no nie ma no XD. W każdym razie - ja poradziłem sobie inaczej. Gdyby ktoś też nie mógł znaleźć tej funkcji - podbijcie to powiem co gdzie wkleić, mam kopie.)_

Ja ukradłem od jakiegoś świeżaka, co miał defaultową listę i skopiowałem jego CSS i potem zaimportowałem ją do siebie i style się pozmieniały, ale tylko style i program nie działał dalej. Później odkryłem, że nadal coś wyróżnia jego listę od mojej. I tak jak wspomniałeś, @Kacper-Kondracki - na mojej była dodatkowa kolumna, bo można w ustawieniach dodać jeszcze chyba 4 kolumny, które domyślnie nie występują.
Sory za usunięcie wiadomości. Myślałem, że nikt nie zdąży zauważyć, a już sobie z tym poradziłem, w każdym razie - dla potomnych, 
**żeby program zadziałał poprawnie należy:**

- Używać oczywiście starej listy, czyli tej spod adresu, gdzie po https:// występuje w pierwszej kolejności słowo"shinden", a nie "lista".
- Mieć defaultowy CSS i ustawienia (kolumny) dla listy (nie grzebać w jej wyglądzie lub przywrócić jej stan fabryczny).
- + Najlepiej jeszcze porównać swoją do jakiejś puli przypadkowych nowych użytkowników, żeby się upewnić, czy czasami nie macie czegoś "za dużo" albo za mało. 

Po zastosowaniu do powyższego - jestem już szczęśliwym posiadaczem konta na MAL'u, a tam po kilku poprawkach, które już wprowadziłem sam + dodaniem kilku skryptów do Tampermonkey - w końcu jestem w mimo wszystko najwygodniejszym miejscu do czytania i dowiadywania się rzeczy o tych przeklętych, chińskich bajkach.

**Wielkie podziękowania oczywiście do @Kacper-Kondracki** za samą inicjatywę. Dziękuję też za trafne podpowiedzi, choć udało mi się wpaść na to wcześniej, to i tak dziękuję za Twój czas.

Swoją drogą, gdyby zawrzeć w readme te informacje powyżej, to w zasadzie nie musiałbyś przepisywać programu. 
Z tego, co zdążyłem "podejrzeć" bebechy shindena w międzyczasie, to raczej nie pozbędą się oni tej "klasycznej/starej" listy. Cały czas jest ona podstawą niektórych funkcjonalności. 
// No chyba, że po prostu z zajawki, to jasne, czemu nie 😃

**Comment by Kacper-Kondracki** [comment]
Wydano nową odsłonę programu
