### ISSUE TITLE
to samo dla Animezone.pl

### ISSUE THREAD

**Issue by Methosss** [AbdShullah/ShindenToAnilist#2]
zrobił byś to samo dla tej strony animezone.pl?

**Comment by Kacper-Kondracki** [comment]
Tak, po przeglądzie strony animezone, konwertowanie wydaje się możliwe
W tym wypadku jeżeli dobrze rozumiem:
Lista ocenionych = obejrzane
Lista oglądanych = oglądane
Lista planowanych = planowane

Z kolei patrząc na listę ulubionych to myślę, że używanie jej do konwersji jest niepraktyczne gdyż ludzie na tej stronie to sobie dodają po 200 anime do ulubionych, gdzie typowo na stronach MAL, Anilist do ulubionych dodaje się pare tytułów.

Po sprawdzeniu strona nie wydaje się mieć ustawionego agresywnego rate limit, więc scrapowanie z niej nie powinno być upierdliwe.

Tak czy inaczej aplikacja ma zostać przepisana od nowa, piorytetem ma być obsługa shindena, i zrobienie bardziej przyjemnego interfejsu użytkownika, i ułatwienie w postaci możliwości łatwiejszego przypisywania nieznalezionych serii już w samej aplikacji

**Comment by rurzowiutki** [comment]
Warto zaznaczyć, że Animezone się sprzedaje, co za tym idzie — widać, że to się nie trzyma i w ogóle posiadanie akurat tam swojej listy jest trochę ryzykowne. Radziłbym na szybko listę spisać, póki to jeszcze stoi. Jakkolwiek.
Zdecydowanie lepszą, polską opcją, która pozwala bardzo łatwo dokopać się do oglądania online, jak i listy, jest ogladajanimepl, czy chociażby docchi, a nawet anime-desu. 
Strony typu Animezone, czy Shinden każą Ci się przekopywać przez kilka podstron, zanim się doczłapiesz do serwera z odcinkiem, a chociażby po ich designie można łatwo stwierdzić, że są po prostu nieaktualizowane, „stare” i o ile to dla części osób może być plus, o tyle sporą grupę może zniesmaczyć w 2024 roku. Odrobina CSS'a by nikomu nie zaszkodziła.

Z Animezone poradziłbym Ci @Methosss się ręcznie przenieść na MAL'a, czy Anilist, o ile masz mniej, niż nie wiem, 100-200 tytułów? Jak masz 1k, no to faktycznie może być kłopot. Ale i tak — wziąłbym jakieś narzędzie typu rozszerzenia do przeglądarki, takie, jak FireShot i chociaż zescreenował sobie całą listę od góry do dołu, żeby tego nie pogubić.

Z kolei @Kacper-Kondracki - zdecydowanie lepiej byłoby się skupić najpierw na najpopularniejszych stronach, łatwiej wówczas będzie zwrócić uwagę na Twój projekt. Nie da się ukryć, że Shinden do nich należy, ale do tego już soft istnieje, a zapowiadasz zrobienie jakiegoś przyjemnego GUI, więc w ogóle klasa, mogąc dodać do opisu zrzuty ekranu z tego jak dobrze wygląda program i jak łatwo z niego skorzystać na pewno zwróci na to uwagę więcej osób, niż obecnie, gdy jest taki raw.
Za to, po ilości ocen jednak widać, że Animezone nie gra tu nawet drugich, czy trzecich skrzypiec i to bym zostawił raczej na później. Słusznie przyznajesz, że Shinden to priorytet. Czas najwyższy, żeby Poloki też zasmakowały tego, co dobre, szczególnie, że MAL jest zwyczajnie warty zaufania. 

// Swoją drogą, to napisałem kilka skryptów, które razem pozwolą, żeby MAL wyglądał nam jeszcze lepiej i był bliższy temu, co dotychczas część osób miała na Shinden, pozwolę sobie wstawić małą próbkę tego, jak może wyglądać nasza strona tytułu na MAL'u. Dużo osób się tu odnajdzie, tak sądzę.

![obraz_2024-02-09_020619416](https://github.com/Kacper-Kondracki/ShindenToAnilist/assets/96441372/3b3f2227-f10a-4bfa-b035-90137c4fcb20)

**Comment by Kacper-Kondracki** [comment]
Już powoli GUI powstaje, po zrobieniu dla shindena zrobienie dla pozostałych to będzie raczej pikuś, zrobię najpierw takie podstawowe pobieranie konwertowanie, po tym zaimplementuje inne serwisy, a na końcu dobieranie, opcje ręcznej korekcji niedopasowanych anime.
![image](https://github.com/Kacper-Kondracki/ShindenToAnilist/assets/43544435/6090dc9c-9b15-467c-9a9b-b71897c3b6c4)

**Comment by Methosss** [comment]
@rurzowiutki 

Ja na szczęście jestem użytkownikiem MyAnimeLista (ze względu na popularność jak i prostote i customizacje listy) jak i Anilist'a (ze względu na śliczny wygląd, nielimitowane ulubione postaci i wykresy ulubionych gatunków) obie się dla mnie uzupełniają.

Chcę przenieść listę znajomemu który sam nie ma na to czasu a i tytułów ma tyle że ma 10 stron tego łącznie i fakt, nie za fajnie by było gdyby strona siadła, NA SZCZĘŚCIE dzięki temu że dałem propozycję Koderowi, na OglądajAnime już jest importer z Anime-Zone więc lista nie przepadnie. Chciałem też koderowi zasugerować by używał bazy danych mal'a albo kompatybilnej, w końcu większość stron korzysta z tego, nie rozumiem czemu akurat w polsce każdy robi bazę anime po swojemu która jak na złość nie nadaje się do niczego w innych serwisach.

//swoją drogą zacnie to wygląda - w sensie skórka na mal'a

ps. @Kacper-Kondracki  lepiej dać możliwość manualnie wklejenia linku do profilu by uniknąć konieczności przepisywania programu bo się np. zmieniła domena. jak to już miało miejsce z tego co widzę po historii zgłoszeń. Samo gui jednak wygląda naprawdę super :)

**Comment by rurzowiutki** [comment]
@Methosss 

Aaa, czyli to dla kogoś, kumam, dobry z Ciebie kolega a takim razie xd. 
No, a skoro ma już listę na oglądaj, to gitara, tam powinna być bezpieczna, ale dobrze też przechowywać ją lokalnie, rzecz jasna.

Jeśli chodzi o AniList, to mam wrażenie, że strony tytułów są bardzo zbliżone graficznie do docchi.pl, samo w sumie docchi wydaje się też trzymać poziom i choć jest tam narazie naprawdę mało pozycji, to rozwijając się robi coraz większe wrażenie i może zrobić na rodzimym rynku zamieszanie. Kolorystyka z kolei przypomina Webtoon'a, aż do bólu. Z drugiej strony - Forum, to zwyczajny, w dodatku darmowy gotowiec. Co do strony głównej, to pewności nie mam, ale to pewnie też jakaś templatka. Co za tym idzie - nie wiem, czy tam cokolwiek powstało from scratch, ale trzeba przyznać, że przynajmniej wygląda na 2024 rok i to pozwala mi przymykać oko na pewne sprawy.

// Z kolei to, czego może Ci brakować na MAL'u, a jest na Anilist da się łatwo załatwić.
Jak widzisz po mnie - MAL też potrafi wyglądać dobrze, o ile się o to zadba, a to naprawdę błahostka. Jak Cię to zainteresuje, to napisałem na MALu prosty poradnik.
Jest bardzo prężnie działająca grupa (w tym też trochę i ja, choć bardziej prywatnie) osób, które tworzą mnóstwo skryptów na dosłownie wszystko, co tylko mogłoby Ci się nie podobać. 
Do przeglądarki instalujesz jakieś rozszerzenie do iniekcji skryptów, np. Tampermonkey (rozszerzenie z polskim akcentem swoją srogą 🤤), a do niego możesz dodać masę skryptów, które będą reagowały i uruchamiały się tylko, gdy odwiedzanym adresem będzie myanimelist.
Gwarantuję, że na przeglądanie nie ma to absolutnie żadnego wpływu, a nawet lepiej - w końcu akurat moja wersja odchudza MAL o masę szajsu, którego nie potrzebuję i mogę porównać się z innym użytkownikiem i mam wykresy. Ba, mogę nawet zdecydować, czy chce wykres liniowy, słupkowy, czy kołowy i wybrać które z właściwości jaki mają mieć kolor. To samo widzę na swoim profilu, to Ty ostatecznie zdecydujesz jaką formę to przybierze.
Finalnie - większość tego, poza listą - zobaczysz tylko Ty, ale co z tego? To Tobie ma być wygodnie 😆.

/ Apropos listy - do niej też mam taki fajowy skrypt, który pokazuje mi kolumnę z oceną z MAL z dwoma miejscami po przecinku i mogę posortować listę na przykład zgodnie z MAL-ową oceną, co zwykle nie jest możliwe. Albo na przykład oglądane obecnie od ilości już obejrzanych epizodów. A zaznaczając tytuł możesz od razu odczytać wszystkie szczegóły, naprawdę tam można magię robić.
MAL + Tampermonkey + GreasyFork i naprawdę moznA wykopać złoto.

**Comment by Kacper-Kondracki** [comment]
Konwertowanie listy z animezone powinno już działać
